"""Канонические имена характеристик и дефолтные веса матчинга.

Одна и та же характеристика приходит от скраперов под разными
названиями (`power`, `потребление питания`, `энергопотребление`).
`canonicalize_spec_name` приводит их к единому ключу, чтобы матчер
сравнивал сопоставимые значения.

`WEIGHT_DEFAULTS` задаёт вес характеристики в формуле взвешенной
суммы: ключевые параметры (разрешение, питание, температурный
диапазон) — выше, косметика — ниже.

`EXCLUDE_SPECS` содержит имена, которые попадают в `product_specs`
ошибочно (URL картинок, артикул, бренд, маркетинговый мусор скрапера).
Матчер их игнорирует.

Источник синонимов — реальное распределение `spec_name` из
`products_specs` клиента. Новые имена дописываются сюда же.
"""

from __future__ import annotations

from typing import Optional


SPEC_ALIASES: dict[str, str] = {
    "power": "power",
    "питание": "power",
    "потребление питания": "power",
    "потребляемая мощность": "power",
    "максимальное потребление питания": "power",
    "энергопотребление": "power",
    "выход питания": "power",
    "источник питания": "power_source",

    "напряжение электропитания (в)": "voltage",
    "напряжение питания шины": "voltage",
    "напряжение питания от шины (в)": "voltage",
    "входное напряжение": "voltage",
    "локальное питание (в)": "voltage",
    "выходное напряжение": "voltage_out",
    
    #"макс. потребляемый ток (ма)": "current",
    #"потребление в режиме ожидания (ма)": "standby_current",
    #"максимальный ток подключаемой нагрузки": "max_load_current",
    #"максимальное постоянное напряжение нагрузки": "max_dc_load",
    #"максимальное переменное напряжение нагрузки": "max_ac_load",

    "экран": "display",
    "дисплей": "display",
    "тип панели": "display_type",
    "режимы дисплея": "display_modes",
    "яркость": "brightness",
    "контрастность": "contrast",
    "сенсорный экран": "touchscreen",
    "соотношение сторон": "aspect_ratio",
    "разрешение экрана": "display_resolution",
    "разрешение (пиксели)": "display_resolution",
    "разрешение": "display_resolution",
    "resolution": "display_resolution",
    "макс. разрешение": "display_resolution",
    "диагональ экрана в дюймах": "display_size",
    "размер дисплея в дюймах": "display_size",

    "камера": "camera",
    "camera": "camera",
    "видеокамера": "camera",
    "встроенная камера": "camera",
    "вспомогательная камера": "aux_camera",
    "разрешение камеры": "camera_resolution",
    "разрешение видеокамеры": "camera_resolution",
   # "минимальная освещённость": "min_illumination",
    #"минимальная освещенность": "min_illumination",
    "сенсор": "sensor",
    #"матрица": "sensor",
    "тип объектива": "lens_type",
    "угол обзора": "view_angle",
    #"ночная подсветка": "night_vision",
    #"ночной режим": "night_mode",
    #"режим работы камеры": "camera_mode",
    #"баланс белого": "white_balance",
    "датчик освещённости": "light_sensor",
    "датчик освещенности": "light_sensor",
    "инфракрасный датчик": "ir_sensor",
    "датчик движения": "motion_sensor",
    "датчик температуры": "temperature_sensor",
    "поддержка hdr": "hdr_support",
    #"скорость кадров": "fps",

    "видеостандарт": "video_codec",
    "видеосжатие": "video_codec",
    "кодеки": "video_codec",
    "сжатие": "video_codec",
    "выходное видео": "video_output",
    "видеовыход": "video_output",
    "аудиокодеки": "audio_codec",
    "аудиосжатие": "audio_codec",
    "аудио": "audio",
    "аудиовход": "audio_in",
    "аудиовыход": "audio_out",
    "аудиовход/выход": "audio_io",
    "интерфейс аудио": "audio_io",
    "аналоговый аудиовыход": "audio_out",
    "линейный выход": "audio_out",
    "динамик": "speaker",
    "микрофон": "microphone",
    #"широкополосный кодек": "wideband_codec",
    #"узкополосные кодеки": "narrowband_codecs",
    #"шумоподавление": "noise_suppression",
    #"эхоподавление": "echo_suppression",
    #"активация голосом": "voice_activation",
    #"битрейт аудио": "audio_bitrate",
    #"качество потоковой трансляции": "stream_quality",
    #"основной поток": "main_stream",
    #"дополнительный поток": "sub_stream",
    #"запись": "recording",

    "температурный режим": "temperature_range",
    "рабочая температура": "temperature_range",
    "диапазон рабочих температур (°c)": "temperature_range",
    "температура хранения": "storage_temperature",
    "рабочая влажность": "humidity_range",
    "допустимая влажность при эксплуатации": "humidity_range",
    "рабочие условия": "operating_conditions",

    "класс защиты": "ip_rating",
    "класс защиты (ip)": "ip_rating",
    "класс степени защиты": "ip_rating",
    "класс защиты от влаги и пыли": "ip_rating",
    "степень защиты корпуса": "ik_rating",
    "степень защиты от ударов": "ik_rating",
    "ik-код": "ik_rating",

    #"интерфейс": "interface",
    #"интерфейс связи": "interface",
    #"интерфейс управления": "control_interface",
    #"сетевой интерфейс": "network_interface",
    #"сеть": "network",
    "беспроводная сеть": "wireless_network",
    "протокол": "protocol",
    "протоколы": "protocol",
    "поддержка sip": "sip",
    "voip-стандарт": "voip_standard",
    "rtsp": "rtsp",
    "onvif": "onvif",
    "поддержка nvr": "nvr",
    "поддержка bluetooth": "bluetooth",
    "версия bluetooth": "bluetooth_version",
    "wi-fi": "wifi",
    "поддерживаемые стандарты wi-fi": "wifi",
    "поддержка wi-fi": "wifi",
    "стандарт беспроводной передачи данных": "wireless_standard",
    "безопасность беспроводной связи": "wireless_security",
    "диапазон частот беспроводной связи (мгц)": "wireless_frequency",
    "рабочая частота": "wireless_frequency",
    "мощность сигнала gsm egsm (дбм)": "gsm_signal_power",
    "dtmf": "dtmf",

    "порт ethernet": "ethernet_port",
    "количество lan портов": "lan_port_count",
    "ip-адрес по умолчанию": "default_ip",
    "порт rs485": "rs485",
    "порт wiegand": "wiegand",
    "интерфейсы wiegand": "wiegand",
    "порт wiegand / rs485": "interface",
    "2-проводные порты": "two_wire_ports",
    "интерфейсы osdp": "osdp",
    "выходов реле": "relay_outputs",
    "релейные выходы (а макс.)": "relay_outputs",
    "релейные выходы (=в макс.)": "relay_outputs",
    "встроенные реле": "relay_outputs",
    "управление реле": "relay_control",
    "выходы управления внешними светодиодами": "led_outputs",
    "сигнальные входы": "alarm_inputs",
    "вход тампера (вскрытие корпуса)": "tamper_input",
    "слот для sd-карт": "sd_slot",
    "вход hdmi": "hdmi_input",
    #"тревожный интерфейс": "alarm_interface",
    "дополнительные разъёмы": "extra_ports",
    "дополнительные разъемы": "extra_ports",
    "порт расширения": "expansion_port",

    "poe": "poe",
    "питание poe": "poe",
    "стандарт poe": "poe_standard",
    "количество портов poe": "poe_port_count",
    "количество портов uplink": "uplink_port_count",
    "метод подачи питания на poe портах": "poe_method",
    "максимальная суммарная мощность всех портов": "max_total_power",
    "максимальная мощность на каждом poe порту": "max_power_per_port",
    "максимальная длина кабеля при подключении к poe портам": "max_poe_cable",
    "уровень коммутатора": "switch_level",

    #"контроль доступа": "access_control",
    #"интеграция со скуд": "access_control",
    #"аутентификация": "authentication",
    #"количество идентификаторов в памяти панели": "id_capacity",
    #"максимальное количество идентификаторов": "id_capacity",
    #"записей карт": "id_capacity",
    #"записей пользователей": "id_capacity",
    #"максимальное количество временных профилей": "time_profile_count",
    #"максимальное количество правил доступа": "access_rules_count",
    #"максимальное количество записей журнала": "log_capacity",
    #"записей журнала": "log_capacity",
    #"записей pin-кодов": "pin_capacity",
    #"количество абонентов": "subscriber_count",
    #"количество sip-аккаунтов": "sip_accounts",

    "считыватель": "reader",
    "считыватель карт": "card_reader",
    "rf считыватель карт": "rf_reader",
    "тип карт": "card_type",
    "идентификация по распознаванию лиц": "face_recognition",
    "режимы распознавания": "recognition_modes",
    "скорость распознавания": "recognition_speed",
    "расстояние считывания": "read_distance",

    "открытие замка": "lock_release",
    #"подключаемые замки": "connectable_locks",
    #"бустер питания для электрозамка": "lock_power_booster",
    #"звуковой сигнал открытия двери": "door_open_sound",
    #"подключение датчика двери": "door_sensor_connection",
    #"подключение сигнализации": "alarm_connection",
    #"пожарная сигнализация": "fire_alarm",
    #"подключение кнопки звонка": "bell_button_connection",
    #"подключение контроллеров": "controller_connection",
    #"подключение считывателей": "reader_connection",
    #"управляемый выход при поступлении входящего звонка": "call_controlled_output",
    #"расстояние срабатывания": "trigger_distance",
    #"защита от демонтажа": "anti_tamper",
    #"защита от взлома": "anti_tamper",
    #"входов для звонка": "call_inputs",
    #"входов тревожных датчиков": "alarm_inputs",
    #"входов": "alarm_inputs",
    #"порт usb": "usb_port",
    #"порт hdmi": "hdmi_port",
    #"порт для гарнитуры": "headset_port",
    #"зуммер": "buzzer",
    #"поддержка резервного источника питания": "backup_battery",
    #"поддержка автоответчика": "answering_machine",
    #"поддержка qos": "qos_support",
    #"расширяемый модуль": "expansion_port",
    #"среда использования": "environment",
    #"безопасность": "security",
    #"тактильный датчик": "touch_sensor",
    #"типы карт": "card_type",
    #"системное время": "system_time",
    #"речевой режим": "talk_mode",
    #"передняя панель": "front_panel",
    #"автоматическое усиление": "auto_gain",
    #"форматы": "video_codec",
    #"индикаторы": "led_indicators",
    #"led индикаторы": "led_indicators",
    #"размер с монтажным коробом": "install_dimensions",

    "вес": "weight",
    "цвет": "color",
    "цветовое решение": "color",
    "корпус": "housing",
    "материал": "material",
    "материал корпуса": "material",
    "технология": "technology",
    "ресурс работы": "lifespan",

    "размеры": "dimensions",
    "размер": "dimensions",
    "габаритные размеры (мм)": "dimensions",
    "высота (мм)": "height",
    "ширина (мм)": "width",
    "глубина (мм)": "depth",
    #"глубина при встроенном монтаже (мм)": "depth_flush",
    #"глубина при настенном монтаже (мм)": "depth_surface",
    #"размеры под установку": "install_dimensions",
    #"размеры упаковки дхшхв (мм)": "package_dimensions",

    "тип монтажа": "mount_type",
    "тип установки": "mount_type",
    "варианты монтажа": "mount_type",
    "монтаж": "mount_type",
    "крепление": "mount_type",
    #"кронштейн для врезного монтажа": "flush_mount_bracket",

    "тип домофона": "device_type",
    "тип интеркома": "device_type",
    "тип клавиатуры": "keyboard_type",
    "тип кнопки": "button_type",
    "кодонаборная клавиатура": "keypad",
    "кнопка вызова": "call_button",

    #"количество кнопок": "button_count",
    #"кнопки": "button_count",
    #"подсветка": "backlight",
    #"количество мелодий вызова": "ringtone_count",
    #"загрузка пользовательских mp3-мелодий": "custom_ringtone",
    #"режим разговора": "talk_mode",
    #"режим «не беспокоить»": "dnd_mode",
    #"режим «без звука»": "silent_mode",
    #"режим «ожидания»": "standby_mode",
    #"автоответчик": "answering_machine",
    #"бэкап фото во время вызова": "call_photo_backup",
    #"поддержка получения сообщений": "message_support",
    #"интерфейс индукционной петли": "induction_loop",

    "операционная система": "os",
    "память": "memory",
    "ram / rom": "memory",
    #"обновление программного обеспечения": "firmware_update",
    "мобильное приложение": "mobile_app",
    #"поддержка сторонних приложений": "third_party_apps",
    #"поддержка сторонних виджетов": "third_party_widgets",
    #"управление домашней автоматикой": "home_automation",
    #"сценарии": "scenarios",
    #"мультимедиа возможности": "multimedia",
    #"выбор типа заставки в режиме ожидания": "screensaver",
    #"функция памяти": "memory_function",
    #"сброс": "reset",

    #"объём карт памяти": "card_capacity",
    #"тип карт памяти": "memory_card_type",

    "ip-камеры": "ip_camera_count",
    #"количество ip-камер": "ip_camera_count",
    #"количество индивидуальных вызывных панелей": "panel_count",
    #"количество многоквартирных вызывных панелей": "multi_panel_count",
    #"подключение дополнительных мониторов": "extra_monitors_connection",

    #"кол-во номеров телефона для вызова (шт.)": "phone_number_count",
    #"макс. кол-во номеров телефона (шт.)": "phone_number_count",

    #"диапазон измерения": "measurement_range",
    #"расстояние измерения": "measurement_distance",
    #"точность измерения": "measurement_accuracy",
    #"тип поддерживаемых координатно-матричных систем": "matrix_systems",

    #"особенности": "features",

    #"резервный аккумулятор": "backup_battery",
    #"независимые линии питания внешних устройств": "external_power_lines",
    #"отдельное питание x2": "power_x2",
}


EXCLUDE_SPECS: frozenset[str] = frozenset({
    "image",
    "source_sku",
    "price",
    "description",
    "артикул",
    "производитель",
    "модель",
    "isavailable",
    "isdeleted",
    "общее",
    "основное",
    "тип",
    "функции",
    "проектный",
    "дополнительно",
    "амиком - официальный дистрибьютор hikvision и hiwatch 107023, "
    "москва, пл. журавлева, 2с2",
    # модельные коды, ошибочно попавшие в spec_name
    "s532", "s532ip", "s562", "s562w", "s563", "s563w", "s565", "s565w",
    "s567", "s567g", "s567w", "r29c", "r29c-b", "e12s", "e12n", "e12w",
    "e21a", "e21v", "it88a", "it88s", "x912k", "x912s", "x933w", "x933s",
    "c313s", "c313w", "c313w-2", "c315s", "c315w", "c316s", "c316w",
    "c319a", "c319s",
    # закомментированные алиасы — ток и нагрузка
    "макс. потребляемый ток (ма)",
    "потребление в режиме ожидания (ма)",
    "максимальный ток подключаемой нагрузки",
    "максимальное постоянное напряжение нагрузки",
    "максимальное переменное напряжение нагрузки",
    # камера
    "минимальная освещённость",
    "минимальная освещенность",
    "матрица",
    "ночная подсветка",
    "ночной режим",
    "режим работы камеры",
    "баланс белого",
    "скорость кадров",
    # аудио
    "широкополосный кодек",
    "узкополосные кодеки",
    "шумоподавление",
    "эхоподавление",
    "активация голосом",
    "битрейт аудио",
    "качество потоковой трансляции",
    "основной поток",
    "дополнительный поток",
    "запись",
    # интерфейсы / сеть
    "интерфейс",
    "интерфейс связи",
    "интерфейс управления",
    "сетевой интерфейс",
    "сеть",
    "тревожный интерфейс",
    # контроль доступа
    "контроль доступа",
    "интеграция со скуд",
    "аутентификация",
    "количество идентификаторов в памяти панели",
    "максимальное количество идентификаторов",
    "записей карт",
    "записей пользователей",
    "максимальное количество временных профилей",
    "максимальное количество правил доступа",
    "максимальное количество записей журнала",
    "записей журнала",
    "записей pin-кодов",
    "количество абонентов",
    "количество sip-аккаунтов",
    # замки и подключения
    "подключаемые замки",
    "бустер питания для электрозамка",
    "звуковой сигнал открытия двери",
    "подключение датчика двери",
    "подключение сигнализации",
    "пожарная сигнализация",
    "подключение кнопки звонка",
    "подключение контроллеров",
    "подключение считывателей",
    "управляемый выход при поступлении входящего звонка",
    "расстояние срабатывания",
    "защита от демонтажа",
    "защита от взлома",
    "входов для звонка",
    "входов тревожных датчиков",
    "входов",
    "порт usb",
    "порт hdmi",
    "порт для гарнитуры",
    "зуммер",
    "поддержка резервного источника питания",
    "поддержка автоответчика",
    "поддержка qos",
    "расширяемый модуль",
    "среда использования",
    "безопасность",
    "тактильный датчик",
    "типы карт",
    "системное время",
    "речевой режим",
    "передняя панель",
    "автоматическое усиление",
    "форматы",
    "индикаторы",
    "led индикаторы",
    "размер с монтажным коробом",
    # габариты
    "глубина при встроенном монтаже (мм)",
    "глубина при настенном монтаже (мм)",
    "размеры под установку",
    "размеры упаковки дхшхв (мм)",
    # монтаж
    "кронштейн для врезного монтажа",
    # кнопки и звонки
    "количество кнопок",
    "кнопки",
    "подсветка",
    "количество мелодий вызова",
    "загрузка пользовательских mp3-мелодий",
    "режим разговора",
    "режим «не беспокоить»",
    "режим «без звука»",
    "режим «ожидания»",
    "автоответчик",
    "бэкап фото во время вызова",
    "поддержка получения сообщений",
    "интерфейс индукционной петли",
    # ПО и приложения
    "обновление программного обеспечения",
    "поддержка сторонних приложений",
    "поддержка сторонних виджетов",
    "управление домашней автоматикой",
    "сценарии",
    "мультимедиа возможности",
    "выбор типа заставки в режиме ожидания",
    "функция памяти",
    "сброс",
    # карты памяти
    "объём карт памяти",
    "тип карт памяти",
    # количество устройств
    "количество ip-камер",
    "количество индивидуальных вызывных панелей",
    "количество многоквартирных вызывных панелей",
    "подключение дополнительных мониторов",
    # телефония
    "кол-во номеров телефона для вызова (шт.)",
    "макс. кол-во номеров телефона (шт.)",
    # измерения
    "диапазон измерения",
    "расстояние измерения",
    "точность измерения",
    "тип поддерживаемых координатно-матричных систем",
    # прочее
    "особенности",
    "резервный аккумулятор",
    "независимые линии питания внешних устройств",
    "отдельное питание x2",
    # поля без аналитической ценности из реальных данных
    "процессор",
    "пропускная способность",
    "дальность подсветки",
    "далность подсветки",
    "протокол считывателя",
    "назначение",
    "usb интерфейс",
})


WEIGHT_DEFAULTS: dict[str, float] = {
    "display_resolution": 3.0,
    "camera_resolution": 3.0,
    "voltage": 3.0,
    "ip_rating": 2.5,
    "ik_rating": 2.0,
    "temperature_range": 2.5,
    "power": 2.5,
    "protocol": 2.5,

    "interface": 2.0,
    "network_interface": 2.0,
    "control_interface": 1.5,
    "video_codec": 2.0,
    "audio_codec": 2.0,
    "audio_bitrate": 1.0,
    "display_size": 2.0,
    "display_type": 1.5,
    "os": 2.0,
    "access_control": 2.0,
    "authentication": 2.0,
    "face_recognition": 2.0,
    "min_illumination": 2.0,
    "view_angle": 2.0,
    "night_vision": 2.0,
    "sip": 2.0,
    "rtsp": 2.0,
    "onvif": 2.0,
    "voip_standard": 1.5,
    "poe": 2.0,
    "poe_standard": 2.0,

    "current": 1.5,
    "standby_current": 1.5,
    "max_load_current": 1.0,
    "max_dc_load": 1.0,
    "max_ac_load": 1.0,
    "voltage_out": 1.5,
    "power_source": 1.5,
    "sensor": 1.5,
    "lens_type": 1.5,
    "fps": 1.5,
    "video_standard": 1.5,
    "video_output": 1.5,
    "stream_quality": 1.5,
    "audio": 1.0,
    "audio_in": 1.0,
    "audio_out": 1.0,
    "audio_io": 1.0,
    "wifi": 1.5,
    "bluetooth": 1.5,
    "wireless_standard": 1.5,
    "wireless_security": 1.5,
    "wireless_network": 1.5,
    "nvr": 1.5,
    "wireless_frequency": 1.5,
    "gsm_signal_power": 1.0,
    "humidity_range": 1.5,
    "operating_conditions": 1.0,
    "device_type": 1.5,
    "card_type": 1.5,
    "memory_card_type": 1.0,
    "card_capacity": 1.0,
    "card_reader": 1.5,
    "reader": 1.5,
    "rf_reader": 1.5,
    "read_distance": 1.0,
    "rs485": 1.5,
    "wiegand": 1.5,
    "id_capacity": 1.5,
    "subscriber_count": 1.5,
    "relay_outputs": 1.5,
    "camera": 1.5,
    "aux_camera": 1.0,
    "memory": 1.5,
    "firmware_update": 1.0,
    "mobile_app": 1.0,
    "third_party_apps": 1.0,
    "third_party_widgets": 1.0,
    "home_automation": 1.0,
    "ip_camera_count": 1.5,
    "extra_ports": 1.0,
    "alarm_interface": 1.0,
    "alarm_connection": 1.0,
    "lock_release": 1.5,
    "connectable_locks": 1.0,
    "lock_power_booster": 1.0,
    "door_open_sound": 0.5,
    "door_sensor_connection": 1.0,
    "bell_button_connection": 1.0,
    "controller_connection": 1.0,
    "reader_connection": 1.0,
    "call_controlled_output": 1.0,
    "trigger_distance": 1.0,

    "color": 1.0,
    "housing": 1.0,
    "material": 1.0,
    "technology": 1.0,
    "lifespan": 1.0,
    "weight": 1.0,
    "dimensions": 1.0,
    "height": 1.0,
    "width": 1.0,
    "depth": 1.0,
    "depth_flush": 1.0,
    "depth_surface": 1.0,
    "install_dimensions": 1.0,
    "package_dimensions": 0.5,
    "mount_type": 1.5,
    "flush_mount_bracket": 0.5,

    "keyboard_type": 1.5,
    "button_type": 1.0,
    "keypad": 1.5,
    "call_button": 1.0,
    "button_count": 1.0,
    "backlight": 1.0,

    "ringtone_count": 0.5,
    "custom_ringtone": 0.3,
    "talk_mode": 1.0,
    "dnd_mode": 0.5,
    "silent_mode": 0.5,
    "standby_mode": 0.5,
    "answering_machine": 1.0,
    "call_photo_backup": 0.5,
    "message_support": 0.5,
    "induction_loop": 0.5,

    "main_stream": 1.0,
    "sub_stream": 1.0,
    "recording": 1.0,
    "scenarios": 0.5,
    "multimedia": 0.5,
    "screensaver": 0.3,
    "memory_function": 0.5,
    "reset": 0.3,
    "pin_capacity": 1.0,
    "panel_count": 1.0,
    "multi_panel_count": 1.0,
    "extra_monitors_connection": 0.5,
    "phone_number_count": 1.0,
    "measurement_range": 1.0,
    "measurement_distance": 1.0,
    "measurement_accuracy": 1.0,
    "matrix_systems": 1.0,
    "switch_level": 1.5,
    "max_total_power": 1.5,
    "max_power_per_port": 1.5,
    "max_poe_cable": 1.0,
    "poe_port_count": 1.5,
    "uplink_port_count": 1.5,
    "poe_method": 1.5,
    "dtmf": 1.0,
    "recognition_modes": 1.0,
    "features": 0.5,

    "osdp": 1.5,
    "alarm_inputs": 1.5,
    "tamper_input": 1.0,
    "anti_tamper": 1.5,
    "led_outputs": 1.0,
    "time_profile_count": 1.0,
    "access_rules_count": 1.5,
    "log_capacity": 1.0,
    "fire_alarm": 1.5,
    "backup_battery": 1.5,
    "external_power_lines": 1.0,
    "power_x2": 1.0,
    "expansion_port": 1.0,

    "storage_temperature": 2.0,
    "ethernet_port": 1.5,
    "lan_port_count": 1.5,
    "default_ip": 0.5,
    "two_wire_ports": 1.0,
    "speaker": 1.5,
    "microphone": 1.5,
    "wideband_codec": 2.0,
    "narrowband_codecs": 2.0,
    "noise_suppression": 1.5,
    "echo_suppression": 1.5,
    "voice_activation": 1.5,
    "camera_mode": 1.5,
    "white_balance": 1.0,
    "light_sensor": 1.5,
    "night_mode": 1.5,
    "ir_sensor": 1.5,
    "motion_sensor": 1.5,
    "temperature_sensor": 1.5,
    "hdr_support": 1.0,
    "display_modes": 1.0,
    "brightness": 1.0,
    "contrast": 1.0,
    "touchscreen": 1.5,
    "aspect_ratio": 1.0,
    "call_inputs": 1.0,
    "front_panel": 0.5,
    "auto_gain": 1.0,
    "bluetooth_version": 1.0,
    "recognition_speed": 1.0,
    "sip_accounts": 1.5,
    "led_indicators": 0.5,
    "usb_port": 1.0,
    "hdmi_port": 1.0,
    "headset_port": 1.0,
    "buzzer": 0.5,
    "qos_support": 1.0,
    "touch_sensor": 1.0,
    "environment": 0.5,
    "security": 0.5,
    "system_time": 0.5,
}


DEFAULT_WEIGHT = 1.0


def canonicalize_spec_name(name: Optional[str]) -> str:
    """Вернуть каноническое имя характеристики по алиасу.

    Ищет в `SPEC_ALIASES` после чистки: strip, lowercase, замена
    non-breaking пробела и non-breaking дефиса на обычные. Имена из
    `EXCLUDE_SPECS` (URL картинок, артикул, бренд, маркетинговый мусор)
    возвращают пустую строку — матчер их пропустит. Неизвестные имена
    возвращаются в очищенном виде, чтобы две стороны с одинаковым
    написанием всё же могли сравниться. Пустой вход даёт пустую строку.
    """
    if not name:
        return ""
    key = (
        name.strip()
        .lower()
        .replace("\xa0", " ")
        .replace("\u2011", "-")
    )
    if key in EXCLUDE_SPECS:
        return ""
    return SPEC_ALIASES.get(key, key)


def weight_for(canonical: str) -> float:
    """Вернуть вес канонической характеристики для формулы матчинга.

    Для неизвестных ключей возвращает `DEFAULT_WEIGHT` (1.0), чтобы
    незнакомые характеристики учитывались с нейтральным весом, а не
    игнорировались.
    """
    return WEIGHT_DEFAULTS.get(canonical, DEFAULT_WEIGHT)
